defmodule MinhaUniversidade.Repo.Migrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:disciplines) do
      add :university_id,
          references(:universities,
            column: :id,
            name: "disciplines_university_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:disciplines, "disciplines_university_id_fkey")

    alter table(:disciplines) do
      remove :university_id
    end
  end
end
