defmodule MinhaUniversidade.Repo.Migrations.MigrateResources18 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:teachers) do
      add :photo_url, :text
    end
  end

  def down do
    alter table(:teachers) do
      remove :photo_url
    end
  end
end
