defmodule MinhaUniversidade.Repo.Migrations.MigrateResources8 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:reviews) do
      modify :teacher_discipline_id, :uuid, null: false
    end
  end

  def down do
    alter table(:reviews) do
      modify :teacher_discipline_id, :uuid, null: true
    end
  end
end
