defmodule MinhaUniversidade.Repo.Migrations.MigrateResources17 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:verification_requests) do
      add :comment, :text
      add :document, :text, null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "verification_requests_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:verification_requests, "verification_requests_user_id_fkey")

    alter table(:verification_requests) do
      remove :user_id
      remove :document
      remove :comment
    end
  end
end
