defmodule MinhaUniversidade.Repo.Migrations.MigrateResources10 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:reviews) do
      add :recommends?, :boolean, null: false
    end
  end

  def down do
    alter table(:reviews) do
      remove :recommends?
    end
  end
end
