defmodule MinhaUniversidade.Repo.Migrations.MigrateResources14 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :verified?, :boolean, default: false
    end
  end

  def down do
    alter table(:users) do
      remove :verified?
    end
  end
end
