defmodule MinhaUniversidade.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:universities) do
      add :faculty, :text
    end
  end

  def down do
    alter table(:universities) do
      remove :faculty
    end
  end
end
