defmodule MinhaUniversidade.Repo.Migrations.MigrateResources13 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:reviews, [:user_id, :teacher_discipline_id],
             name: "reviews_unique_review_per_user_index"
           )
  end

  def down do
    drop_if_exists unique_index(:reviews, [:user_id, :teacher_discipline_id],
                     name: "reviews_unique_review_per_user_index"
                   )
  end
end
