defmodule MinhaUniversidade.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:universities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text
      add :acronym, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:teachers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text
      add :email, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:teacher_disciplines, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :teacher_id,
          references(:teachers,
            column: :id,
            name: "teacher_disciplines_teacher_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :discipline_id, :uuid
    end

    create table(:reviews, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :rating, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :teacher_discipline_id,
          references(:teacher_disciplines,
            column: :id,
            name: "reviews_teacher_discipline_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:disciplines, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:teacher_disciplines) do
      modify :discipline_id,
             references(:disciplines,
               column: :id,
               name: "teacher_disciplines_discipline_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:disciplines) do
      add :name, :text
      add :code, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:disciplines) do
      remove :updated_at
      remove :inserted_at
      remove :code
      remove :name
    end

    drop constraint(:teacher_disciplines, "teacher_disciplines_discipline_id_fkey")

    alter table(:teacher_disciplines) do
      modify :discipline_id, :uuid
    end

    drop table(:disciplines)

    drop constraint(:reviews, "reviews_teacher_discipline_id_fkey")

    drop table(:reviews)

    drop constraint(:teacher_disciplines, "teacher_disciplines_teacher_id_fkey")

    drop table(:teacher_disciplines)

    drop table(:teachers)

    drop table(:universities)
  end
end
