defmodule MinhaUniversidade.Repo.Migrations.MigrateResources7 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:disciplines), :university_id, to: :faculty_id

    drop constraint(:disciplines, "disciplines_university_id_fkey")

    alter table(:disciplines) do
      modify :faculty_id,
             references(:faculties,
               column: :id,
               name: "disciplines_faculty_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:disciplines, "disciplines_faculty_id_fkey")

    alter table(:disciplines) do
      modify :faculty_id,
             references(:universities,
               column: :id,
               name: "disciplines_university_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    rename table(:disciplines), :faculty_id, to: :university_id
  end
end
