defmodule MinhaUniversidade.Repo.Migrations.MigrateResources11 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:reviews) do
      remove :didactics_comments
    end
  end

  def down do
    alter table(:reviews) do
      add :didactics_comments, :text, null: false
    end
  end
end
