defmodule MinhaUniversidade.Repo.Migrations.MigrateResources19 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:verification_requests) do
      add :applied_university_id,
          references(:universities,
            column: :id,
            name: "verification_requests_applied_university_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    alter table(:users) do
      add :university_id,
          references(:universities,
            column: :id,
            name: "users_university_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:users, "users_university_id_fkey")

    alter table(:users) do
      remove :university_id
    end

    drop constraint(:verification_requests, "verification_requests_applied_university_id_fkey")

    alter table(:verification_requests) do
      remove :applied_university_id
    end
  end
end
