defmodule MinhaUniversidade.Repo.Migrations.MigrateResources9 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:reviews) do
      remove :rating
      add :didactics_rate, :bigint, null: false
      add :didactics_comments, :text, null: false
      add :exams_rate, :bigint, null: false
      add :exams_comments, :text, null: false
      add :enforces_attendance?, :boolean, null: false
      add :enforces_attendance_comments, :text, null: false
      add :geral_rating, :bigint, null: false
      add :geral_comments, :text, null: false
    end
  end

  def down do
    alter table(:reviews) do
      remove :geral_comments
      remove :geral_rating
      remove :enforces_attendance_comments
      remove :enforces_attendance?
      remove :exams_comments
      remove :exams_rate
      remove :didactics_comments
      remove :didactics_rate
      add :rating, :bigint, null: false
    end
  end
end
